### ISSUE TITLE
Axis Deadzone Bug

### ISSUE THREAD

**Issue by Aviage-01** [Codenade/ksp2-inputbinder#18]
Usually a deadzone is mapped such that if the joystick value is between [upper limit] and [lower limt], the output is set to [neutral value], otherwise output = joystick value, so any small fluctuations of the axis when it isn't directly being used don't actually cause the game to act on them.

Currently, you have it mapped such that  if the joystick value is between [upper limit] and [lower limt], the output is set to [neutral value], otherwise output = sign(joystick value). This means it is impossible to both have a deadzone, and then to have any fine control from the same axis.

**Comment by Aviage-01** [comment]
The biggest problem with this is that it means that you can't use SAS while controlling pitch/yaw/roll with an axis, as the axis' minor fluctations prevent SAS from taking control of the aircraft

**Comment by Codenade** [comment]
seems to be working normally with version 0.4.3

**Comment by Codenade** [comment]
I will check it out on experimental

**Comment by Aviage-01** [comment]
Here's some deadzone code I found online (src: https://arduino.stackexchange.com/questions/83413/create-a-dead-zone-for-joystick):

```// Create the dead zone as per Majenko's algorithm.
    val -= ANALOGUE_MID;
    int direction = val < 0 ? -1 : +1;
    val = abs(val);
    val -= ANALOGUE_THRESHOLD;
    if (val < 0) val = 0;

    // Create a new mapped range with a dead zone.
    val *= direction;
    val += ANALOGUE_MID;
    Serial.print(val);
    Serial.print(", ");
    val = map(val, ANALOGUE_MIN + ANALOGUE_THRESHOLD, ANALOGUE_MAX - ANALOGUE_THRESHOLD, SERVO_MIN, SERVO_MAX);
    Serial.println(val);```
    
Which is different to your documentation for AxisDeadZone:

![image](https://github.com/Codenade/ksp2-inputbinder/assets/37037463/88056ec4-9c56-4d01-8085-f21c81b84d1b)

That might help?

**Comment by Codenade** [comment]
The code is fine I just didn't formulate the documentation correctly, this is the actual math going on:
```cs
float Process(float value)
{
    float num = Mathf.Abs(value);
    if (num < min)
    {
        return 0f;
    }
    if (num > max)
    {
        return Mathf.Sign(value);
    }
    return Mathf.Sign(value) * ((num - min) / (max - min));
}
```
The documentation already has links in the headings to the official documentation from Unity, though no one would notice because the headings are blue by default. It might be best if I just put a link to the Unity documentation instead of my version.

**Comment by Aviage-01** [comment]
Oh, that makes more sense. Thanks for the clarification!
