### ISSUE TITLE
Bug in adding additional control fields

### ISSUE THREAD

**Issue by Aviage-01** [Codenade/ksp2-inputbinder#20]
I am attempting to set the ability to zoom the camera in and out from my joystick during flight, so I placed 'Flight.activeCameraZoom' in the game_actions_to_add.txt file, and rebooted the game, but no option is appearing for it in the in-game mod GUI.
![image](https://github.com/Codenade/ksp2-inputbinder/assets/37037463/e9aa4adc-4b85-4e1c-8ffb-84fee7807bd9)

**Comment by Codenade** [comment]
Hello @Aviage-01 which version of the mod are you using?

**Comment by Aviage-01** [comment]
The experimental one you just gave me

**Comment by Codenade** [comment]
Wow it seems you got lucky ... or unlucky, you picked the exact one that doesn't seem to work! XD
Im currently investigating what causes this.

**Comment by Codenade** [comment]
Oh I see the devs changed the available actions. I need to update documentation.
This means you should use `Flight.CameraZoom`.
There is still a problem: the binding cannot be changed yet. I'll have something figured out soon.

**Comment by Codenade** [comment]
Known issue: Cannot load this binding:
![20-inputbinder](https://github.com/Codenade/ksp2-inputbinder/assets/19842648/c27a5fff-08af-4522-8316-3df16f7eaca4)
Working on it right now.

**Comment by Codenade** [comment]
Blocked on #25

**Comment by Aviage-01** [comment]
It's not just that binding - down and up also don't load correctly.
