### ISSUE TITLE
Load non-functional

### ISSUE THREAD

**Issue by Aviage-01** [Codenade/ksp2-inputbinder#21]
I created a copy of the input.json file, and when there was a bug which caused the mod to forget about all axes (except throttle, for some reason), I overrode the input.json file with the copy. However, neither pressing the load button, nor rebooting the game and mod, caused the mod to use the settings from the new input.json file.

**Comment by Codenade** [comment]
Thanks for bringing this to my attention @Aviage-01 !
Which version of the mod are you using?

**Comment by Codenade** [comment]
Should be working now (PR #25)
