### ISSUE TITLE
Feature Request: Automatically add scale processor

### ISSUE THREAD

**Issue by Aviage-01** [Codenade/ksp2-inputbinder#23]
It would be really nice if, when you assign a button to an axis controller, it automatically adds a 'scale = 15' modifier.

**Comment by Codenade** [comment]
This will for now be a config setting.

**Comment by Codenade** [comment]
Hey @Aviage-01 just wanted to let you know that I updated the experimental release with the changes form #29.
I am now updating the wiki pages and will then push a new full release.
