### ISSUE TITLE
Slider scale not corresponding to range

### ISSUE THREAD

**Issue by Aviage-01** [Codenade/ksp2-inputbinder#24]
When you need to input a number into a modifier, such as a scale amount, the scalar value can be (and often needs to be) any float value. Yet the slider only allows the direct input of values between 0 and 1. Fortunately the direct entry text box allows this to be bypassed, but the slider seems a bit misleading, and doesn't seem particularly useful.

**Comment by Codenade** [comment]
I agree that the range is not particularly useful expecially because no negative value can be set. I will change the default range to make it more useful. I am thinking about maybe a range from -2 to +2, I will make it configureable somehow tho.

**Comment by Aviage-01** [comment]
Whatever you think's best.
