### ISSUE TITLE
SAS controls

### ISSUE THREAD

**Issue by jorntmeister** [Codenade/ksp2-inputbinder#36]
Hi! Love the mod, it would be realy nice if I could bind the different SAS modes to my custom controler. The rest is working, only buttons that i can't use yet are the different SAS modes.
Idk if it's possible but would be super nice.

Thanks either way!

**Comment by Codenade** [comment]
I will look into this on the weekend.

**Comment by Codenade** [comment]
I'm assuming you want to set these modes:

![image](https://github.com/Codenade/ksp2-inputbinder/assets/19842648/38e9a55b-0fde-4688-946d-0bec66b94b2d)

**Comment by jorntmeister** [comment]
Yes exactly, that would be super nice!

**Comment by Codenade** [comment]
You can download the latest build [here](https://github.com/Codenade/ksp2-inputbinder/actions/runs/7597325994/artifacts/1183355899) from github actions.

**Comment by jorntmeister** [comment]
Just tested it, it works great! Thank you so much!
