### ISSUE TITLE
Escape key not working when this is installed

### ISSUE THREAD

**Issue by linuxgurugamer** [Codenade/ksp2-inputbinder#37]
### Description

When this is installed, the escape key is not working

### Steps to reproduce

Install mod
Start game
Press Esc

### Expected behaviour

Esc is supposed to bring up a menu on the left

**Comment by Codenade** [comment]
> If you are not supporting this anymore, please let me know and I can look into adopting it

Thanks but I'm still planning on supporting it.

**Comment by linuxgurugamer** [comment]
Great, thank you.

I've tried out the changes, they seem to be working nicely.
