### ISSUE TITLE
Feature request:  Allow both a key binding and a controller binding

### ISSUE THREAD

**Issue by linuxgurugamer** [Codenade/ksp2-inputbinder#40]
### Description

While testing the ESC fix, I noticed that once I set a binding for a joystick, the key binding went away.

It would be nice if there could be both a key binding and a joystick binding (main/alternative binding).  Not sure if this is possible, though

### Steps to reproduce

n/a

### Expected behaviour

main and alt bindings possible

**Comment by Codenade** [comment]
Having main and alternate bindings should already be possible by assingning controls to the marked bindings:
![Screenshot (31)](https://github.com/Codenade/ksp2-inputbinder/assets/19842648/f3276ef6-e695-49de-91fb-21462e11006c)
![Screenshot (33)](https://github.com/Codenade/ksp2-inputbinder/assets/19842648/151677c9-c28f-4173-83a7-5c482fe33998)

**Comment by Codenade** [comment]
Hey @linuxgurugamer is this still an active issue?

**Comment by linuxgurugamer** [comment]
Apparently not
I'll close this, but would appreciate knowing when you are planning on doing the next release.

**Comment by Codenade** [comment]
@linuxgurugamer I'm planning a new release on the weekend.
