### ISSUE TITLE
Can't hold SAS control with joystick on and input binder enabled

### ISSUE THREAD

**Issue by stenner11t1** [Codenade/ksp2-inputbinder#44]
### Description

input binder works great for planes, cudos.  For everything that requires SAS the SAS will not hold attitiude and either yaws or rolls or both in certain directions.   My joystick monitor claims it's not giving inputs, but with the joystick off it does hold SAS.   With input binder off and native controls (albeit bad) it holds SAS.   But with the two together it's unplayable.  

I don't know much about coding or what this issue is but any help is appreciated. thanks.

### Steps to reproduce

Have a joystick plugged in and enabled, attempt to use SAS control in space in KSP 2.

### Expected behaviour

SAS works when I turn the joystick off or unplug it.

### Additional information

I don't know what I can provide but I'll do whatever I can to make it work.

**Comment by Codenade** [comment]
Hey @stenner11t1 have you tried adding deadzones to yaw, pitch and roll?

**Comment by stenner11t1** [comment]
Will try right now, thanks.

**Comment by stenner11t1** [comment]
@Codenade also it's now doing the inputs with sas off, with deadzones, I checked everything I can check on the stick itself, but thanks, I'm gonna fiddle around and try and figure this out.

**Comment by Codenade** [comment]
Hey @stenner11t1 you might have set the deadzones incorrectly. The AxisDeadzone processor's min argument defines the size of the inner deadzone while the max argument defines the outer deadzone. If the normalized input value is lower than min, it will forward a value of 0 to the game. If the normalized input value is greater than max, it will forward a value of 1 or -1 to the game. Inbetween your controls will work normally.

Please try if setting min=0.15 and max=1 fixes your issue.

**Comment by stenner11t1** [comment]
Okay so in my lack of description I may have omitted some things which  I guess I knew but forgot about.  I have set the deadzones.   it did not help sadly.  also thanks for your reply!  I greatly appreciate you taking the time.

But the thing I forgot was, I have a vkb nxt stick and it has a monitor, the monitor keeps saying there's no input from the stick.

But I can even "reset all" wich removes all my sticks bindings, and sas will still let any vessel spin wildly and not hold attitiude.  the only thing that stops it, even being unbound, is turning off the stick.   I have no idea how to explain how it happens.

**Comment by stenner11t1** [comment]
@Codenade massivle apologies.  my save is cursed.  if I restart the game and make a new file, the deadzone seems to have worked once I did it properly, i just needed to launch a new save or get out of my cursed save.    

I loadied up the game after some trouble and it seems to work with my stick and SAS, I'm beyond happy, thanks.
