### ISSUE TITLE
Throttle starts in center instead of at 0?

### ISSUE THREAD

**Issue by RadioFreeKerbin** [Codenade/ksp2-inputbinder#49]
### Description

Throttle axis has 0 in the center position instead of the fully back position. Should there be a setting or processor to ensure the throttle position doesn't include negative axis positions? Or am I just not seeing the option to configure this?

### Steps to reproduce

This is using a Saotek X-55 Rhino throttle unit. Flight stick is a Thrustmaster T.16000M and it has the same issue. 

### Expected behaviour

Throttle uses the entire length of the slider to adjust thrust

**Comment by Codenade** [comment]
If I understand this correctly you have a control that ranges from -1 to +1 and want to map it to the throttle with a range from 0 to 1. To do this you could use the [Map Processor](https://github.com/Codenade/ksp2-inputbinder/wiki/Input-Processors#map):

`Map(in_min=-1,in_max=1,out_min=0,out_max=1)`

or if your controller's throttle axis is inverted:

`Map(in_min=1,in_max=-1,out_min=0,out_max=1)`

**Comment by RadioFreeKerbin** [comment]
Thank you so much! 

Also, I wanted to ask if there was a reason why there wasn't a thread posted for this mod on the official [KSP2 Mod Releases forum](https://forum.kerbalspaceprogram.com/forum/130-ksp2-mod-releases/)? That way, other users might be able to answer simple questions like this and not leave it all up to you, as well as ask feature related questions without filing a bug report?

**Comment by Codenade** [comment]
Well I created a thread inside the KSP2 Modding Society discord server and I guess I just forgot about the forum post. 
I believe however making one shouldn't be a problem!
