### ISSUE TITLE
Possible to add clamp processors to pitch/roll/yaw bindings?

### ISSUE THREAD

**Issue by nanonestor** [Codenade/ksp2-inputbinder#51]
### Description

I have a Thrustmaster T16000M FCS joystick - I've found that I can bind the the joystick pitch and yaw because in the joystick they count as stick/left, stick/right, stick/up, stick/down, however iI can't seem to find anything to make roll bind to the joystick twist correctly.

(What works fine for regular pitch/yaw)
```
"overridePath": "/Thrustmaster T.16000M/stick/up"
},
{
"overridePath": "/Thrustmaster T.16000M/stick/down"
```
I *can* bind Roll to the twist (rz) axis of the joystick, however it will only go in one direction.  I think the solution could be as some have done in regular game settings to put a clamp on the value for each side of the control when set for each direction in the binding.

(Works but only for one direction)
```
"overridePath": "/Thrustmaster T.16000M/rz"
```

(How I would think you're supposed to format it assuming clamps are valid to be used.  I did try to edit the config manually like this and did not work.)
```
    "Roll": {
      "bindings": [
        {},
        {
          "overridePath": "/Thrustmaster T.16000M/rz",
          "overrideProcessors": "Clamp(min=-1,max=0)"
        },
        {
          "overridePath": "/Thrustmaster T.16000M/rz",
          "overrideProcessors": "Clamp(min=0,max=-1)"
        },
        {},
        {
          "overridePath": ""
        },
        {
          "overridePath": ""
        },
        {}
      ]
    },
```

As the title asks - is it possible to let these values allow clamps?  Or perhaps it already does and i'm doing it wrong?  Thanks!

### Steps to reproduce

Uh - can try with a joystick

### Expected behaviour

Detection of a joystick twist as an axis control I guess would be nice, but probably not feasible?  Allowing clamps or any processors for any values would be nice.

**Comment by Codenade** [comment]
For axes you should use the marked binding:

![273062284-db0b9c32-2467-4108-a456-4065a09ad081.png](https://github.com/Codenade/ksp2-inputbinder/assets/19842648/4696ff10-a83e-4dd5-9561-f2f3f82ac62f)

**Comment by Codenade** [comment]
> Detection of a joystick twist as an axis control I guess would be nice, but probably not feasible? 

Hey @nanonestor have you tried to assign the twist axis to the last binding?

![273062284-db0b9c32-2467-4108-a456-4065a09ad081.png](https://github.com/Codenade/ksp2-inputbinder/assets/19842648/6b4db5b0-779c-4809-b456-49c7aac2457e)

-------

In addition:

```json
    "Roll": {
      "bindings": [
        {
          // This is where you can add processors however you cannot
          // bind controls here as this is the main binding of the
          // composite binding and its path defines what type of
          // composite binding it is.
        },
        {
          "overridePath": "/Thrustmaster T.16000M/rz",
          "overrideProcessors": "Clamp(min=-1,max=0)"
          // Processors added here won't work as this is part of a
          // composite binding and you can only add processors to the
          // main binding of a composite binding.
        },
        {
          "overridePath": "/Thrustmaster T.16000M/rz",
          "overrideProcessors": "Clamp(min=0,max=-1)"
        },
        {},
        {
          "overridePath": ""
        },
        {
          "overridePath": ""
        },
        {
           // Assigning your axis here should work:
           // "overridePath": "/Thrustmaster T.16000/rz"
        }
      ]
    },
```

> Composite Bindings are Bindings consisting of multiple parts, which form a Control together. For instance, a [2D Vector Composite](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.3/manual/ActionBindings.html#2d-vector) uses four buttons (left, right, up, down) to simulate a 2D stick input. See the [Composite Bindings](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.3/manual/ActionBindings.html#composite-bindings) documentation to learn more.
> \- [Unity InputSystem documentation](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.3/manual/ActionAssets.html#editing-composite-bindings)

**Comment by nanonestor** [comment]
Thank you got it!  I had been focusing on the composite bindings and had been disregarding the 'Axis binding' as it looked innocuous.  Maybe consider adding something to the readme.md to help PEBKAC cases like myself? :D


```
    "Roll": {
      "bindings": [
        {},
        {
          "overridePath": ""
        },
        {
          "overridePath": ""
        },
        {},
        {
          "overridePath": ""
        },
        {
          "overridePath": ""
        },
        {
          "overridePath": "/Thrustmaster T.16000M/rz",
          "overrideProcessors": "Invert();AxisDeadzone(min=-0.10,max=0.10)"
        }
      ]
    },
```

**Comment by Codenade** [comment]
No problem, also for the AxisDeadzone processor you might want to set min=0.1 and max=1. This is described [here](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.3/manual/Processors.html#axis-deadzone).

**Comment by nanonestor** [comment]
Ah.  I see, would never have guessed that was how 'deadzone' was determined without that documentation.  Thanks.

**Comment by Codenade** [comment]
> If it's not too much trouble perhaps your wiki could include descriptions in human-language on what each processor does?

I will open a new issue for this and other sources of confusion.
